abstract: generates CPAN like pod pages
author: Lyo Kato <lyo.kato@gmail.com>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Pod-ProjectDocs
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Syntax::Highlight::Universal: 0
requires: 
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  File::Basename: 0
  File::Copy: 0
  File::Find: 0
  File::Spec: 0
  JSON: 2.04
  MIME::Base64: 0
  Pod::ParseUtils: 0
  Pod::Parser: 1.32
  Readonly: 0
  Template: 0
  URI::Escape: 0
version: 0.35
